name: make Datapack
on:
 push:
   tags:
     - "MC*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: module Zip
        uses: montudor/action-zip@v1

      - name: Create zip
        run: zip -qq -r datapack.zip *
        working-directory: Structure_reloading_datapack

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: MC-1.20.2_EN
          release_name: Minecraft 1.20.2 and more (EN)
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Structure_reloading_datapack/datapack.zip
          asset_name: Structure_reloading_${{ github.ref_name }}.zip
          overwrite: true
          body: |
            tested for Minecraft: 1.20.2, 1.20.4, 1.20.6
            The latest version of the datapack for this version of Minecraft is : Structure_reloading_${{ github.ref_name }}.zip
             ||
            \\/